version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.9.28-management
    restart: always
    ports:
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=!Development123
  
  postgres:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=!Development123
  
  #pgadmin:
  #  image: dpage/pgadmin4:6.20
  #  volumes:
  #    - pgadmin-data:/var/lib/pgadmin
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=dev@dev.dev
  #    - PGADMIN_DEFAULT_PASSWORD=!Development123
  #  ports:
  #    - "2345:80"

volumes:
  rabbitmq-data:
  postgres-data:
  #pgadmin-data:  