name: Create Release
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
      deploy:
        type: boolean
        description: Deploy
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Signals.App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Signals.App/Dockerfile
          tags: ghcr.io/rudenwork/signals.app:${{ github.event.inputs.tag }}
          push: true
          
  deploy:
    name: Deploy
    needs: create-release
    if: github.event.inputs.deploy
    uses: rudenwork/signals/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      tag: ${{ github.event.inputs.tag }}
