name: Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Read compose file
        id: readcompose
        run: echo "COMPOSE=$(cat .github/stack/compose.yml)" >> $GITHUB_OUTPUT
            
      - name: Deploy Portainer stack
        uses: LGinC/portainer-stack-deploy@1.0
        with: 
          serverurl: ${{ secrets.PORTAINER_URL }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          endpointId: 2
          stackname: signals
          docker_compose: ${{ steps.readcompose.outputs.COMPOSE }}
          env: |
            TAG=${{ github.event.inputs.version }}
