name: Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
            
      - name: Deploy Portainer stack
        uses: LGinC/portainer-stack-deploy@1.0
        with: 
          serverurl: ${{ secrets.PORTAINER_URL }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          endpointId: 2
          stackname: signals
          env: |
            TAG=${{ github.event.inputs.version }}
          docker_compose: |
            version: '3.9'
            services:
              signals.test:
                image: ghcr.io/rudenwork/signals.test:$TAG
                restart: always  
