name: Deploy
on: 
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
