name: Docker Build Push
on: workflow_dispatch
jobs:
  build-push-docker-image:
    name: Build Docker image and push 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./Signals.Test
          tags: ghcr.io/rudenwork/signals.test:v0.0
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
