name: Publish
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        default: dev
      app:
        type: boolean
        description: Signals.App
      web:
        type: boolean
        description: Signals.Web
jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Signals.App
        if: inputs.app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Signals.App/Dockerfile
          tags: ghcr.io/rudenwork/signals.app:${{ inputs.tag }}
          push: true

      - name: Build Signals.Web
        if: inputs.web
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Signals.Web/Dockerfile
          tags: ghcr.io/rudenwork/signals.web:${{ inputs.tag }}
          push: true
